export const ROLES = {
  USER: "user",
  VENDOR: "vendor",
  ADMIN: "admin",
};

export const STATUS_CODES = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
};

export const MESSAGES = {
  SUCCESS: {
    SIGNUP: "Signup successful. Please verify your email.",
    LOGIN: "Login successful",
    LOGOUT: "Logout successful",
    OTP_SENT: "OTP sent to your email",
    OTP_VERIFIED: "OTP verified successfully",
    OTP_RESENT: "OTP resent successfully",
    PASSWORD_RESET: "Password reset successful",
    PROFILE_UPDATED: "Profile updated successfully.",
    PASSWORD_UPDATED: "Password changed successfully.",
    USERS_FETCHED: "Users fetched successfully",
    VENDORS_FETCHED: "Vendors fetched successfully",
    PENDING_VENDORS_FETCHED: "Pending vendors fetched successfully",
    PENDING_VENUES_FETCHED: "Pending venues fetched successfully",
    APPROVED_VENUES_FETCHED: "Approved venues fetched successfully",
    VENDOR_APPROVED: "Vendor approved successfully",
    VENDOR_REJECTED: "Vendor rejected successfully",
    VENDOR_BLOCKED: "Vendor blocked successfully",
    VENDOR_UNBLOCKED: "Vendor unblocked successfully",
    USER_BLOCKED: "User blocked successfully",
    USER_UNBLOCKED: "User unblocked successfully",
    VENUE_APPROVED: "Venue approved successfully",
    VENUE_REJECTED: "Venue rejected successfully",
    VENUE_CREATED: "Venue added successfully",
    VENUE_UPDATED: "Venue updated successfully",
    VENUE_FETCHED: "Venues fetched successfully",
    BOOKING_FETCHED: "Booking fetched successfully",
    BOOKING_CREATED: "Booking created successfully",
    PAYMENT_VERIFIED: "Payment verified and booking confirmed",
    BOOKING_DATES_FETCHED: "Booked dates fetched successfully",
    BLOCKED_DATE_ADDED: "Blocked date added successfully",
    REVENUE_FETCHED: "Revenue fetched successfully",
    BOOKING_CANCELLED: "Booking cancelled successfully.",
    REVIEW_CREATED: "Review created successfully.",
    REVIEW_FETCHED: "Reviews fetched successfully.",
    REPLY_ADDED: "Reply added successfully",
    REVIEW_DELETED: "Review deleted successfully",
    MESSAGE_SENT: "Message sent successfully",
    CONVERSATION_FETCHED: "Conversation fetched successfully",
    CONVERSATIONS_FETCHED: "Conversations fetched successfully",
    NOTIFICATION_CREATED: "Notification created successfully",
    NOTIFICATIONS_FETCHED: "Notifications fetched successfully",
    NOTIFICATION_UPDATED: "Notification updated successfully",
    TRANSACTION_HISTORY_FETCHED: "Transaction history fetched successfully",
  },
  ERROR: {
    INVALID_CREDENTIALS: "Invalid credentials",
    EMAIL_EXISTS: "Email already exists",
    USER_NOT_FOUND: "User not found",
    INVALID_INPUT: "Invalid input: Email and Password are required",
    PASSWORD_MISMATCH: "Password and Confirm Password do not match",
    PROFILE_UPDATE_FAILED: "Profile update failed.",
    JWT_SECRET_MISSING: "JWT secret is not configured",
    OTP_INVALID: "Invalid OTP",
    OTP_EXPIRED: "OTP has expired",
    UNAUTHORIZED: "Unauthorized access",
    FORBIDDEN: "Forbidden access",
    SERVER_ERROR: "Internal server error",
    MISSING_FIELDS: "Required fields are missing",
    INVALID_TOKEN: "Invalid or expired token",
    ALREADY_VERIFIED: "User is already verified",
    BLOCKED: "You have been blocked by the admin",
  },
};