
const TYPES = {
  //CONTROLLERS
  AuthController: Symbol.for("AuthController"),
  UserController: Symbol.for("UserController"),
  InstructorController: Symbol.for("InstructorController"),
  CourseController: Symbol.for("CourseController"),
  ModuleController: Symbol.for("ModuleController"),
  LessonController: Symbol.for("LessonController"),
  CategoryController: Symbol.for("CategoryController"),
  CartController: Symbol.for("CartController"),
  PaymentController: Symbol.for("PaymentController"),
  OrderController: Symbol.for("OrderController"),
  EnrollmentController: Symbol.for("EnrollmentController"),
  WebhookController: Symbol.for("WebhookController"),
  TransactionController: Symbol.for("TransactionController"),
  WalletController: Symbol.for("WalletController"),
  AdminController: Symbol.for("AdminController"),
  ReviewController: Symbol.for("ReviewController"),
  PayoutController: Symbol.for("PayoutController"),
  CertificateController: Symbol.for("CertificateController"),
  NotificationController: Symbol.for("NotificationController"),
  ChatController: Symbol.for("ChatController"),
  MessageController: Symbol.for("MessageController"),
  

  //SERVICES
  AuthService: Symbol.for("AuthService"),
  UserService: Symbol.for("UserService"),
  InstructorService: Symbol.for("InstructorService"),
  CourseService: Symbol.for("CourseService"),
  ModuleService: Symbol.for("ModuleService"),
  LessonService: Symbol.for("LessonService"),
  CategoryService: Symbol.for("CategoryService"),
  CartService: Symbol.for("CartService"),
  PaymentService: Symbol.for("PaymentService"),
  OrderService: Symbol.for("OrderService"),
  EnrollmentService: Symbol.for("EnrollmentService"),
  WebhookService: Symbol.for("WebhookService"),
  TransactionService: Symbol.for("TransactionService"),
  WalletService: Symbol.for("WalletService"),
  AdminService: Symbol.for("AdminSerive"),
  ReviewService: Symbol.for("ReviewService"),
  PayoutService: Symbol.for("PayoutSerivce"),
  CertificateService: Symbol.for("CertificateService"),
  NotificationService: Symbol.for("NotificationService"),
  ChatService: Symbol.for("ChatService"),
  MessageService: Symbol.for("MessageService"),

  //REPOSITORIES
  AuthRepository: Symbol.for("AuthRepository"),
  UserRepository: Symbol.for("UserRepository"),
  InstructorRepository: Symbol.for("InstructorRepository"),
  CourseRepository: Symbol.for("CourseRepository"),
  ModuleRepository: Symbol.for("ModuleRepository"),
  LessonRepository: Symbol.for("LessonRepository"),
  CategoryRepository: Symbol.for("CategoryRepsoitory"),
  CartRepository: Symbol.for("CartRepository"),
  OrderRepository: Symbol.for("OrderRepository"),
  EnrollmentRepository: Symbol.for("EnrollmentRepository"),
  TransactionRepository: Symbol.for("TransactionRepository"),
  WalletRepository: Symbol.for("WalletRepository"),
  AdminRepository: Symbol.for("AdminRepository"),
  ReviewRepository: Symbol.for("ReviewRepository"),
  PayoutRepository: Symbol.for("PayoutRepository"),
  CertificateRepository: Symbol.for("CertificateRepository"),
  NotificationRepository: Symbol.for("NotificationRepository"),
  ChatRepository: Symbol.for("ChatRepository"),
  MessageRepository: Symbol.for("MessageRepository"),
};

export default TYPES;
